/**
 * Pure module for Dashboard quick-select → Bookmark management deep linking.
 * Contains only pure contract functions for generating URL query on StatsDashboard row click (buildDrilldownUrl)
 * and consuming it once upon BookmarkList onMount in Bookmark management tab (parseDrilldownParams).
 * Allows unit testing without environment dependencies such as window.location.
 */

// Uncategorized folder sentinel — generated by stats-tracker getFolderDistribution as folderPath || '기타'.
export const UNCATEGORIZED_SENTINEL = '기타';

export type Drilldown =
  | { kind: 'host'; host: string }
  | { kind: 'folder'; folder: string }
  | { kind: 'tag'; tag: string };

/**
 * Generates a deep link URL from basePath (window.location.pathname).
 * - host: empty string / whitespace only → null (navigation prohibited).
 * - tag: empty string / whitespace only / '#' only → null, removes leading '#', URL encoded.
 * - folder === UNCATEGORIZED_SENTINEL('기타') → replaced with filter=uncategorized
 *   (prevents 0-item malfunction when assigning '기타' to selectedFolder).
 * - Other folder → &folder=<encodeURIComponent(original folderPath)>
 */
export function buildDrilldownUrl(basePath: string, d: Drilldown): string | null {
  if (d.kind === 'host') {
    if (!d.host || d.host.trim() === '') return null;
    return `${basePath}?tab=bookmarks&host=${encodeURIComponent(d.host)}`;
  }

  if (d.kind === 'tag') {
    const tag = d.tag?.trim().replace(/^#/, '');
    if (!tag) return null;
    return `${basePath}?tab=bookmarks&tag=${encodeURIComponent(tag)}`;
  }

  const folder = d.folder;
  if (!folder || folder.trim() === '') return null;
  if (folder === UNCATEGORIZED_SENTINEL) {
    return `${basePath}?tab=bookmarks&filter=uncategorized`;
  }
  // E7: Pass original folderPath string as-is (do not re-normalize).
  return `${basePath}?tab=bookmarks&folder=${encodeURIComponent(folder)}`;
}

export interface DrilldownParams {
  /** → searchQuery (host substring match) */
  host?: string;
  /** → selectedFolder (original folderPath, prefix subtree match) */
  folder?: string;
  /** → selectedFilters = ['uncategorized'] */
  filterUncategorized?: boolean;
  /** → selectedTag */
  tag?: string;
}

/**
 * Parses deep link intent from location.search. All properties are optional and consumed only once on BookmarkList onMount.
 * - Single-dimension mutually exclusive priority: host > filter > folder > tag.
 * - host/folder/tag: ignored if present but contains only whitespace.
 * - filter: false for values other than 'uncategorized'.
 */
export function parseDrilldownParams(search: string): DrilldownParams {
  const params = new URLSearchParams(search);
  const host = params.get('host');
  const filter = params.get('filter');
  const folder = params.get('folder');
  const tag = params.get('tag');

  const result: DrilldownParams = {};
  if (host && host.trim() !== '') {
    result.host = host.trim();
    return result;
  }
  if (filter === 'uncategorized') {
    result.filterUncategorized = true;
    return result;
  }
  if (folder && folder.trim() !== '') {
    result.folder = folder;
    return result;
  }
  if (tag && tag.trim() !== '') {
    const cleanTag = tag.trim().replace(/^#/, '');
    if (cleanTag !== '') {
      result.tag = cleanTag;
      return result;
    }
  }
  return result;
}